trigger:
  - main

pool:
  vmImage: "ubuntu-latest"

variables:
  imageName: "cloudnautic/pythonapp"
  serviceConnection: "acr-connection"

steps:
  - task: Docker@2
    displayName: "Build and Push Docker Image to ACR"
    inputs:
      containerRegistry: "$(serviceConnection)"
      repository: "$(imageName)"
      command: "buildAndPush"
      Dockerfile: "**/Dockerfile"
      tags: |
        $(Build.BuildId)
        latest