trigger:
  - main

pool:
  vmImage: "ubuntu-latest"

variables:
  imageName: "atulkamble.azurecr.io/cloudnautic/pythonapp"

steps:
  - task: Docker@2
    displayName: "Build and Push Docker Image to ACR "
    inputs:
      containerRegistry: "acr-connection"
      repository: "$(imageName)"
      command: "buildAndPush"
      Dockerfile: "**/Dockerfile"
      tags: |
        $(Build.BuildId)
        latest
